version: "3"

services:

  condominio-webapp:
    image: felipedibernardi/condominio-webapp
    networks:
      - dev-network
    ports:
      - 80:8080
    depends_on:
      - database

  database:
    image: felipedibernardi/condominio-database
    networks:
      - dev-network
    volumes:
      - "mydata:/var/lib/mysql"

volumes:
  mydata:

networks:

  dev-network: